/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_read_MainActivity */
#ifndef _Included_com_example_read_MainActivity
#define _Included_com_example_read_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
// 宏定义类似java 层的定义,不同级别的Log LOGI, LOGD, LOGW, LOGE, LOGF。 对就Java中的 Log.i log.d
#define LOG_TAG    "hpc -- JNILOG" // 这个是自定义的LOG的标识
//#undef LOG // 取消默认的LOG
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG, __VA_ARGS__)
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG, __VA_ARGS__)
#define LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG, __VA_ARGS__)
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG, __VA_ARGS__)
#define LOGF(...)  __android_log_print(ANDROID_LOG_FATAL,LOG_TAG, __VA_ARGS__)
/*
 * Class:     com_example_read_MainActivity
 * Method:    printJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_read_MainActivity_printJNI
  (JNIEnv *, jobject);
/*
 * Class:     com_example_read_MainActivity
 * Method:    result
 * Signature: ([[I)[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_read_MainActivity_result
  (JNIEnv *, jobject, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif
