/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_app_jni_Recognize */

#ifndef _Included_net_app_jni_Recognize
#define _Included_net_app_jni_Recognize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_app_jni_Recognize
 * Method:    recognize
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_net_app_jni_Recognize_recognize
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
